image: maven:3.5.4-jdk-8

stages:
  - test
  - analyze
  
unit_test:
  stage: test
  script:
    - mvn clean test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

analyze:
  stage: analyze
  image: maven:3.6.3-jdk-11
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=ciproject2
  rules:
    - merge_requests
    - master
    - develop