image: maven:3.5.4-jdk-8

services:
    - postgres:12.2-alpine
variables:
  POSTGRES_DB: qieam
  POSTGRES_USER: Cyriel
  POSTGRES_PORT: 5432
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL_TEST: 'postgres://Cyriel:@postgres:5432/qieam'

stages:
  - test
  - analyse
  
unit_test:
  stage: test
  script:
    - mvn clean test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

sonar_analyse:
  stage: analyse
  image: maven:3.6.3-jdk-11
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=ciproject2

postgres_service:
  stage: postgres
  
  script:
    - export DATABASE_URL_TEST=postgres://Cyriel:@postgres:5432/qieam